### ISSUE TITLE
Readme has image output at .jpg but arnt they pngs?

### ISSUE THREAD

**Issue by gateway** [rkhamilton/vqgan-clip-generator#17]
I was looking at the readme today and noticed  ```        output_filename = 'output.jpg')``` at various parts of the examples but are you not output a proper png? :? :) Typo?

**Comment by rkhamilton** [comment]
Thanks, that is a mistake in the docs. The example code will still run, but it will generate output.jpg.png as the output.

I’m regretting that I take output filenames as the base name without the file extension. The rationale is that the user can’t pick the file type. They will always be png. The only thing you can specify is the base name before the extension. However, that ends up being a little annoying because you want to actually use the file name in scripts and internal code. It would have been better to just sanity check the output file and if it doesn’t end in .png to throw an error. I may convert to that method at some point.

Docs are fixed.
