### ISSUE TITLE
using style-transfer.py to toy around and getting error

### ISSUE THREAD

**Issue by Byronius7X** [rkhamilton/vqgan-clip-generator#61]
```
(vqgan3) C:\Apps\vqgan-clip-generator\examples>python "style_transfer - Copy.py"
Traceback (most recent call last):
  File "C:\Apps\vqgan-clip-generator\examples\style_transfer - Copy.py", line 34, in <module>
    original_video_frames = video_tools.extract_video_frames(input_video_path,
  File "C:\Users\BRi7X\anaconda3\envs\vqgan3\lib\site-packages\vqgan_clip\video_tools.py", line 29, in extract_video_frames
    raise ValueError(f'input_video_path must be a directory')
ValueError: input_video_path must be a directory

(vqgan3) C:\Apps\vqgan-clip-generator\examples>
```

I've even gone into the python script and changed what I thought this field should be many times, but the video tools script still doesn't like my answer. Might you have any suggestions? Thank you so much! This seems like it's going to become one of my favorite implementations. NerdyRodent's is good, but this seems to have smoothing for video frames which I'm quite into! ^_^ 

EDIT: So I decided to keep trying several more times, finally landing on just moving the video into the examples directory and setting just the filename as input_video_path, and that *appears* to have worked, we shall see how it goes. 

Edit 2: So the first 200 iterations for the first video frame worked, but then the script halted with this:

```
(vqgan3) C:\Apps\vqgan-clip-generator\examples>python "style_transfer - Copy.py"
Traceback (most recent call last):
  File "C:\Apps\vqgan-clip-generator\examples\style_transfer - Copy.py", line 39, in <module>
    metadata_comment = generate.style_transfer(original_video_frames,
  File "C:\Users\BRi7X\anaconda3\envs\vqgan3\lib\site-packages\vqgan_clip\generate.py", line 537, in style_transfer
    output_size_X, output_size_Y = VF.filesize_matching_aspect_ratio(video_frames[0], eng_config.output_image_size[0], eng_config.output_image_size[1])
  File "C:\Users\BRi7X\anaconda3\envs\vqgan3\lib\site-packages\vqgan_clip\_functional.py", line 351, in filesize_matching_aspect_ratio
    img=Image.open(files[0])
IndexError: list index out of range
```
Is this due to something I either didn't modify correctly or missed entirely?
I'm also getting a series of errors with restyle_video.py though I'll hold off on that so as to not overwhelm anyone responding to this.

**Comment by rkhamilton** [comment]
The initial error you were getting (ValueError: input_video_path must be a directory, which is a typo btw, it should read "must be a **file**) is because os.path.isfile(input_video_path) isn't able to find your input file. I've seen a lot of problems like that when there are spaces in the file names or folder names, or maybe special characters. It sounds like you are seeing the same deal here where it doesn't like the file name/path you have. If you can share the value of input_video_path when it throws that error I'd appreciate it, and I can try to dial in the error checking. If you are certain that it's flagging it by mistake, you can comment out lines 28-29 and see if it runs. Please let me know if you find a permanent fix.

Your second error is surprising. I wouldn't expect a failure after it gets into iterations successfully. That error message is because filesize_matching_aspect_ratio() was given an input file that it couldn't open (not an image, didn't exist, etc). Are you using any special characters in your source files? Maybe there's some other files in your directories, and it's trying to open a non-image file? I just pushed  v2.3.1 which has some error checking and will print the name of the file when it gets stuck at that spot. Let me know if you figure it out.

I recommend that you not use restyle_video.py, and instead only work with style_transfer.py as your starting point. Restyle_video is using the older algorithm that doesn't have a lot of improvements that I added to style_transfer. It does result in a different look, which is why I kept the older one.

Thanks for letting me know it was throwing an error though. It turned out I had a bug in my unit test for that example so I didn't know it was broken. It is running for me now. Again, I'd use style_transfer instead, but if you want to try the older version (which should match what you get from NerdyRodent in terms of look), it should work now.

**Comment by Byronius7X** [comment]
I was able to get it started a few times both locally on my laptop and also on the Colab (figured I'd try that since it was more together and probably tested). There were a few errors that it spit out that I was able to comment out a few lines. It seems like it's having some trouble finding directories used. 

When it worked, I noticed the output was only on one frame of the video. Like, it was outputting an animated image sequence, but only on the first frame of video. It was doing this on both the Colab and on my laptop locally. For the record, I was using style_transfer.py as a template and pasting into a notepad++ and changing the fields for my prompts and settings and then pasting it piece by piece into an anaconda actual-python console (versus just the console of anaconda, if that makes sense)

I noticed that I had to comment out changing prompts at a given frame on the colab or else it would spit a type error "int not iterable", which was fine for now. 

I'm thinking for when I got it working, it seems like the init_image is *supposed* to overwrite itself for each frame but is for some reason not doing so. It was doing this on both the colab and on my Windows laptop.

**Comment by rkhamilton** [comment]
The fact that you aren't having success with the colab notebook indicates that you may have something wrong specific to your video file. That colab environment does run the style transfer successfully in my tests.

Given that you are editing my scripts, and copy/pasting the results into an ipython(?) console, I'm not going to be able to help you troubleshoot. I hope you understand there's just no way for me to know what you are doing. Others are using these tools successfully without making those edits and copy/pasting into ipython, so I have to assume something you are doing is responsible the errors you are seeing. Of course, you may be using an unusual video file, or have unusual characters in your path. If so I'd like to know it so I can change my code to accommodate it.

If you'd like me to try to help, you need to run the code as I provided it. In particular if you've edited any of the package files (generate.py, engine.py, etc) you must revert those by uninstalling and reinstalling the package. I won't help troubleshoot if you've made unspecified changes to those files. They're tested and working for [all of the scenarios shown here](https://github.com/rkhamilton/vqgan-clip-generator/tree/main/tests).

1. Update your pacakge and revert any changes you may have made to generate.py or other package files.
2. Create a folder (e.g. C:\vqgan\) 
3. In that folder, download a current copy of [examples/style_transfer.py](https://github.com/rkhamilton/vqgan-clip-generator/blob/main/examples/style_transfer.py). 
4. In that folder, put [THIS specific test source video](https://github.com/rkhamilton/vqgan-clip-generator/blob/main/tests/test_files/small.mp4). Let's rule out a video-specific problem.
5. Edit style_transfer.py line 14 to read input_video_path = 'small.mp4'
6. From your anaconda prompt, change to C:\vqgan, activate your python environment, and run "python style_transfer.py"

If this fails, attach your edited style_transfer.py to your reply here and I'll take a look.

Please also confirm that you are using the latest colab notebook (open it from the repo) and the latest version of the package (v2.3.1). You can see the version using this python code
```python
print(vqgan_clip.__version__)
```

You can revert and reinstall using shell command
```sh
pip uninstall vqgan-clip-generator
pip install git+https://github.com/rkhamilton/vqgan-clip-generator.git
```

And since you mentioned the initial image being overwritten, what you should see in generate.style_transfer() is that an init_image.jpg is generated once for each style transfer. It should not be overwritten. Are you sure you're not running style_transfer_exploration.py, which is intended to generate a bunch of short style transfers with different settings, and save a single image from each set of parameters?

**Comment by Byronius7X** [comment]
So, in both instances (on my laptop and on Google's Colab servers), and with the latest versions of the package, the process seems to have completed with no errors, versus what was happening before, so that's very good! On my computer, I only modified line fourteen to reference the small.mp4 file and left everything else as is. (I reinstalled the package with the commands you've provided and created a fresh directory in C:\vqgan with the style_transfer.py and small.mp4) It seems to have extracted the frames of the video successfully, as before, and then began the style transfer.
 On both the Colab and my local laptop, frames are generated and put in generated_frames. The image sequence in this folder (and the output video created afterward) the effect is animated throughout, but it still appears to be using only the first frame of video. Based on the contents of small.mp4, it should start showing motion by frame 43 when the top starts spinning.
I can link the entirety of the directory to you if that would make it easier to diagnose. Of course, it's using the spider portrait prompt (as that was included initially) and it went rather abstract with it, but I can give it a different prompt if you'd like. 
(RIFE seems to have failed here locally, but it did work when I tried this on Colab.)
Here is the folder that it output: https://drive.google.com/drive/folders/1AaP_D0SA84Dubocb-qjKeD6MZC8gVg0H?usp=sharing 

In the meantime, I'll try another with a different prompt and quicker settings so the original is more visible so you can see the animation doesn't reflect the extracted frames image sequence.

**Comment by rkhamilton** [comment]
I'm glad it's running without error for you. I was able to confirm the bug you are seeing was introduced in the last commit, and I've pushed v2.3.2 with a fix. If you upgrade your package you should find that it works as expected now. Thank you for opening the issue.
```sh
pip install git+https://github.com/rkhamilton/vqgan-clip-generator.git --upgrade
```
