### ISSUE TITLE
RuntimeError: requires_grad_ is not supported on ScriptModules

### ISSUE THREAD

**Issue by timeFliesWhenYoureHavingFun** [rkhamilton/vqgan-clip-generator#71]
Hi, I am trying to run your colab. I believe it's a crucial node in the system because of it's integration of optical flow interpolation  for the AI effects. I am getting this error in the "Style transfer to an existing video" node

[/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py](https://localhost:8080/#) in fail(self, *args, **kwargs)
    912     def _make_fail(name):
    913         def fail(self, *args, **kwargs):
--> 914             raise RuntimeError(name + " is not supported on ScriptModules")
    915 
    916         return fail

RuntimeError: requires_grad_ is not supported on ScriptModules

**Comment by rkhamilton** [comment]
Are you using any special characters in your video file names? Perhaps try it with no spaces or special characters.

**Comment by timeFliesWhenYoureHavingFun** [comment]
Only if numbers are special characters--I am uploading files like Gowanus1.mov,  Gowanus2.mov,  Gowanus3.mov etc

**Comment by timeFliesWhenYoureHavingFun** [comment]
also, thank you so much for replying to my message!

**Comment by rkhamilton** [comment]
I was able to replicate the problem. It looks like Google Colab has updated the version of pytorch they provided by default, and my notebook isn't compatible with the newer version 1.10. I just uploaded a changed notebook that installs pytorch 1.9.0, and that fixes the problem for me. I should have fixed the version number from the start instead of relying on the default pytorch from Google. Please let me know if this fixes things for you as well.

Thank you for opening the issue. I provide colab notebooks for convenience of others, and don't use them myself. I wouldn't have stumbled on this change with Google's default packages if nobody had told me. Cheers!

**Comment by timeFliesWhenYoureHavingFun** [comment]
Amazing it works now! I shared with some AI art friends, we and I, are super appreciative!
